"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { Locale } from "@/i18n/config";

interface PropertyReportProps {
  property: {
    title: string;
    description?: string;
    price: number;
    area: number;
    bedrooms: number;
    bathrooms: number;
    status: string;
    zone?: string;
    type?: string;
    office?: string;
  };
  locale: Locale;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 12, fontFamily: "Helvetica" },
  header: { backgroundColor: "#1B2D4F", color: "#ffffff", padding: 20, marginBottom: 20, borderRadius: 8 },
  title: { fontSize: 24, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#C49A2A", marginBottom: 8 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: "bold", color: "#1B2D4F", marginBottom: 8, borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingBottom: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 0.5, borderBottomColor: "#f3f4f6" },
  label: { color: "#6b7280", fontSize: 11 },
  value: { color: "#1f2937", fontSize: 12, fontWeight: "bold" },
  description: { color: "#4b5563", fontSize: 11, lineHeight: 1.6, marginTop: 8 },
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, textAlign: "center", color: "#9ca3af", fontSize: 9, borderTopWidth: 0.5, borderTopColor: "#e5e7eb", paddingTop: 10 },
  badge: { backgroundColor: "#1B2D4F", color: "#ffffff", padding: 4, borderRadius: 4, fontSize: 10, fontWeight: "bold", alignSelf: "flex-start", marginBottom: 10 },
});

export default function PropertyReportPDF({ property, locale }: PropertyReportProps) {
  const isAr = locale === "ar";
  const formatPrice = (price: number) =>
    new Intl.NumberFormat(isAr ? "ar-EG" : "en-US").format(price) + " EGP";

  const statusLabel = (status: string) => {
    const map: Record<string, { ar: string; en: string }> = {
      available: { ar: "متاح", en: "Available" },
      reserved: { ar: "محجوز", en: "Reserved" },
      sold: { ar: "تم البيع", en: "Sold" },
      rented: { ar: "تم الإيجار", en: "Rented" },
    };
    return map[status]?.[locale] || status;
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{property.title}</Text>
          <Text style={styles.subtitle}>Aqar Cloud</Text>
          <Text style={styles.badge}>{statusLabel(property.status)}</Text>
        </View>

        {/* Property Details */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{isAr ? "تفاصيل العقار" : "Property Details"}</Text>
          <View style={styles.row}>
            <Text style={styles.label}>{isAr ? "السعر" : "Price"}</Text>
            <Text style={styles.value}>{formatPrice(property.price)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{isAr ? "المساحة" : "Area"}</Text>
            <Text style={styles.value}>{property.area} m²</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{isAr ? "غرف النوم" : "Bedrooms"}</Text>
            <Text style={styles.value}>{property.bedrooms}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{isAr ? "الحمامات" : "Bathrooms"}</Text>
            <Text style={styles.value}>{property.bathrooms}</Text>
          </View>
          {property.zone && (
            <View style={styles.row}>
              <Text style={styles.label}>{isAr ? "المنطقة" : "Zone"}</Text>
              <Text style={styles.value}>{property.zone}</Text>
            </View>
          )}
          {property.type && (
            <View style={styles.row}>
              <Text style={styles.label}>{isAr ? "النوع" : "Type"}</Text>
              <Text style={styles.value}>{property.type}</Text>
            </View>
          )}
          {property.office && (
            <View style={styles.row}>
              <Text style={styles.label}>{isAr ? "المكتب" : "Office"}</Text>
              <Text style={styles.value}>{property.office}</Text>
            </View>
          )}
        </View>

        {/* Description */}
        {property.description && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{isAr ? "الوصف" : "Description"}</Text>
            <Text style={styles.description}>{property.description}</Text>
          </View>
        )}

        {/* Footer */}
        <Text style={styles.footer}>
          {isAr ? "تم الإنشاء بواسطة Aqar Cloud" : "Generated by Aqar Cloud"} | {new Date().toLocaleDateString(isAr ? "ar-EG" : "en-US")}
        </Text>
      </Page>
    </Document>
  );
}
