create or replace function public.score_property_match(p_left uuid,p_right uuid) returns jsonb language plpgsql set search_path=public as $$ declare a properties%rowtype; b properties%rowtype; score numeric:=0; reasons jsonb:='[]'::jsonb; begin select * into a from properties where id=p_left; select * into b from properties where id=p_right; if not found then return jsonb_build_object('score',0,'reasons','[]'::jsonb); end if; if lower(coalesce(a.city,''))=lower(coalesce(b.city,'')) and a.city is not null then score:=score+0.15; reasons:=reasons||jsonb_build_array('same_city'); end if; if a.property_type=b.property_type and a.property_type is not null then score:=score+0.10; reasons:=reasons||jsonb_build_array('same_property_type'); end if; if a.transaction_type=b.transaction_type then score:=score+0.10; reasons:=reasons||jsonb_build_array('same_transaction_type'); end if; if a.parcel_number is not null and b.parcel_number=a.parcel_number then score:=score+0.45; reasons:=reasons||jsonb_build_array('same_parcel_number'); end if; if a.area_m2 is not null and b.area_m2 is not null and abs(a.area_m2-b.area_m2)<=0.5 then score:=score+0.15; reasons:=reasons||jsonb_build_array('same_area'); end if; if a.price is not null and b.price is not null and abs(a.price-b.price)<=greatest(1000,least(a.price,b.price)*0.01) then score:=score+0.10; reasons:=reasons||jsonb_build_array('close_price'); end if; return jsonb_build_object('score',least(1,score),'reasons',reasons); end; $$;
create or replace function public.materialize_property_matches(p_property_id uuid) returns integer language plpgsql set search_path=public as $$ declare r record; c jsonb; inserted integer:=0; begin for r in select id from properties where id<>p_property_id and lower(coalesce(city,''))=lower((select city from properties where id=p_property_id)) and coalesce(status::text,'')<>(select coalesce(status::text,'') from properties where id=p_property_id) is not null loop c:=public.score_property_match(p_property_id,r.id); if (c->>'score')::numeric>=0.70 then insert into entity_matches(left_entity_type,left_entity_id,right_entity_type,right_entity_id,match_type,score,reasons,status) values('property',p_property_id,'property',r.id,'property_resolution',(c->>'score')::numeric,c->'reasons','candidate') on conflict do nothing; inserted:=inserted+1; end if; end loop; return inserted; end; $$;
create or replace function public.compute_lead_score(p_person_id uuid,p_property_id uuid) returns jsonb language plpgsql set search_path=public as $$ declare score numeric:=0; reasons jsonb:='[]'::jsonb; c int; begin if p_person_id is null or p_property_id is null then return jsonb_build_object('score',0,'tier','cold','reasons','[]'::jsonb); end if; select count(*) into c from contacts where person_id=p_person_id and verified=true; if c>0 then score:=score+0.20; reasons:=reasons||jsonb_build_array('verified_contact'); end if; if exists(select 1 from property_people where person_id=p_person_id and property_id=p_property_id) then score:=score+0.35; reasons:=reasons||jsonb_build_array('direct_property_relationship'); end if; if exists(select 1 from lead_signals where person_id=p_person_id and score>=0.60 and observed_at>=now()-interval '30 days') then score:=score+0.30; reasons:=reasons||jsonb_build_array('recent_strong_signal'); end if; if lower(coalesce((select city from people where id=p_person_id),''))=lower(coalesce((select city from properties where id=p_property_id),'')) then score:=score+0.15; reasons:=reasons||jsonb_build_array('same_city'); end if; score:=least(1,score); return jsonb_build_object('score',score,'tier',case when score>=0.80 then 'hot' when score>=0.60 then 'warm' when score>=0.35 then 'cool' else 'cold' end,'reasons',reasons); end; $$;
revoke all on function public.score_property_match(uuid,uuid) from public,anon,authenticated;
revoke all on function public.materialize_property_matches(uuid) from public,anon,authenticated;
revoke all on function public.compute_lead_score(uuid,uuid) from public,anon,authenticated;
grant execute on function public.score_property_match(uuid,uuid) to service_role;
grant execute on function public.materialize_property_matches(uuid) to service_role;
grant execute on function public.compute_lead_score(uuid,uuid) to service_role;
